name: Enrich YAML with CVE Details

on: [push]

jobs:

  enrich:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Check if CVE ID exists
      id: check
      run: |
        find . -name '*.yaml' ! -name 'blank.yaml' | xargs grep -l 'cve-id:' | wc -l | xargs echo "::set-output name=exists::"

    - name: Get CVE details
      if: ${{ steps.check.outputs.exists != '0' }}
      run: |
        find . -name '*.yaml' ! -name 'blank.yaml' | xargs grep -o 'CVE-\d+-\d+' | head -n 1 | tee /tmp/cveid
        cve=$(cat /tmp/cveid)
        details=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/CVEProject/cvelist/contents/${cve}.json)
        echo "::set-output name=details::$details"
      id: cve

    - name: Add CVE details
      if: ${{ steps.check.outputs.exists != '0' }}
      run: |
        details="${{ steps.cve.outputs.details }}"
        
        for file in $(find . -name '*.yaml' ! -name 'blank.yaml'); do
        
          yaml=$(echo "$details" | jq -r '.content | @base64d | fromjson')
        
          if [ $? -ne 0 ]; then
            echo "Error parsing JSON: "
            echo "$details"
            exit 1
          fi
        
          yaml="$yaml" jq --argjson add "$yaml" '.metadata += $add' "$file" > "${file}_new"
        
          mv "${file}_new" "$file"
        
        done
