name: CVE Check

on:
  push:
    branches:
      - main

jobs:
  cve_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run CVE Check
        run: python .github/scripts/cve_check.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "CVE check results"
